version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "54320:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - ./.env.prod
    volumes:
      - .:/code
    command: >
      bash -c "python app/db/init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
  bot:
    build: .
    container_name: bot
    depends_on:
      - db
    command: >
      bash -c "python3 bot/main.py"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    env_file:
      - ./.env.prod
    networks:
      - backend
volumes:
  db_data:

networks:
  backend:
